# ---------------------------------------------------------------------------
# "OrdererOrgs" - 定义Orderer组织
# ---------------------------------------------------------------------------
OrdererOrgs:
  # ---------------------------------------------------------------------------
  # Orderer
  # ---------------------------------------------------------------------------
  - Name: Orderer
    Domain: sidechain.com
    EnableNodeOUs: true
    # ---------------------------------------------------------------------------
    # "Specs" - 为Orderer组织中的每个Orderer定义规范
    # ---------------------------------------------------------------------------
    Specs:
      - Hostname: orderer
        SANS:
          - localhost
          - 127.0.0.1

# ---------------------------------------------------------------------------
# "PeerOrgs" - 定义Peer组织
# ---------------------------------------------------------------------------
PeerOrgs:
  # ---------------------------------------------------------------------------
  # Org1
  # ---------------------------------------------------------------------------
  - Name: Org1
    Domain: org1.sidechain.com
    EnableNodeOUs: true
    # ---------------------------------------------------------------------------
    # "Specs"
    # ---------------------------------------------------------------------------
    Specs:
      - Hostname: peer0
        SANS:
          - localhost
          - 127.0.0.1
      - Hostname: peer1
        SANS:
          - localhost
          - 127.0.0.1
    # ---------------------------------------------------------------------------
    # "Template"
    # ---------------------------------------------------------------------------
    Template:
      Count: 0
    # ---------------------------------------------------------------------------
    # "Users"
    # ---------------------------------------------------------------------------
    Users:
      Count: 1
